### ISSUE TITLE
LPC[000]: Got SYNC no-response error. Error address reg: 0xf004202c

### ISSUE THREAD

**Issue by pridhiviraj** [open-power/skiboot#172] opened 2018-04-05 10:27 UTC
After a kernel crash OPAL floods the console with this LPC no-response errors on OpenBMC systems.
```
[console-pexpect]#[17582052845.989499] Oops: Kernel access of bad area, sig: 7 [#1]
[17582052845.993305] LE SMP NR_CPUS=2048 NUMA PowerNV
[17582052845.997756] Modules linked in: vhost_net vhost tap xt_CHECKSUM iptable_mangle ipt_MASQUERADE nf_nat_masquerade_ipv4 iptable_nat nf_nat_ipv4 nf_nat nf_conntrack_ipv4 nf_defrag_ipv4 xt_conntrack nf_conntrack libcrc32c ipt_REJECT nf_reject_ipv4 xt_tcpudp bridge stp llc ebtable_filter ebtables ip6table_filter ip6_tables iptable_filter kvm_hv kvm idt_89hpesx vmx_crypto at24 ofpart uio_pdrv_genirq uio cmdlinepart ipmi_powernv ipmi_devintf ipmi_msghandler powernv_flash ibmpowernv opal_prd crct10dif_vpmsum mtd sch_fq_codel jc42 ip_tables x_tables autofs4 mlx5_ib ib_core nouveau ast mlx5_core i2c_algo_bit ttm drm_kms_helper syscopyarea sysfillrect sysimgblt fb_sys_fops ahci mlxfw crc32c_vpmsum drm tg3 libahci
[17582052845.997756] Modules linked in: vhost_net vhost tap xt_CHECKSUM iptable_mangle ipt_MASQUERADE nf_nat_masquerade_ipv4 iptable_nat nf_nat_ipv4 nf_nat nf_conntrack_ipv4 nf_defrag_ipv4 xt_conntrack nf_conntrack libcrc32c ipt_REJECT nf_reject_ipv4 xt_tcpudp bridge stp llc ebtable_filter ebtables ip6table_filter ip6_tables iptable_filter kvm_hv kvm idt_89hpesx vmx_crypto at24 ofpart uio_pdrv_genirq uio cmdlinepart ipmi_powernv ipmi_devintf ipmi_msghandler powernv_flash ibmpowernv opal_prd crct10dif_vpmsum mtd sch_fq_codel jc42 ip_tables x_tables autofs4 mlx5_ib ib_core nouveau ast mlx5_core i2c_algo_bit ttm drm_kms_helper syscopyarea sysfillrect sysimgblt fb_sys_fops ahci mlxfw crc32c_vpmsum drm tg3 libahci
[52479.130024] KVM: CPU 69 seems to be stuck
[52479.130024] KVM: CPU 69 seems to be stuck
[17582052845.998534]  devlink
[17582052845.998534]  devlink
[17582052845.998559] CPU: 69 PID: 0 Comm: swapper/69 Not tainted 4.15.0-13-generic #14-Ubuntu
[17582052845.998559] CPU: 69 PID: 0 Comm: swapper/69 Not tainted 4.15.0-13-generic #14-Ubuntu
[17582052845.998583] NIP:  c0000000000ec87c LR: c0000000000ec6ac CTR: 000000000000006c
[17582052845.998583] NIP:  c0000000000ec87c LR: c0000000000ec6ac CTR: 000000000000006c
[17582052845.998595] REGS: c00000003fcc3c70 TRAP: 0300   Not tainted  (4.15.0-13-generic)
[17582052845.998595] REGS: c00000003fcc3c70 TRAP: 0300   Not tainted  (4.15.0-13-generic)
[17582052845.998596] MSR:  9000000002803033 <SF,HV,VEC,VSX,FP,ME,IR,DR,RI,LE>  CR: 44400888  XER: 00000000
[17582052845.998596] MSR:  9000000002803033 <SF,HV,VEC,VSX,FP,ME,IR,DR,RI,LE>  CR: 44400888  XER: 00000000
[17582052845.998711] CFAR: c0000000000ec818 DAR: 0006030203190010 DSISR: 02000002 SOFTE: 0 
[17582052845.998711] GPR00: 0000000000000001 c00000003fcc3ef0 c0000000016eaf00 007fffffffffeb25 
[17582052845.998711] GPR04: c0000017208d5540 c0000016d4185900 0000000000000000 ffffffffffffffff 
[17582052845.998711] GPR08: 0040000003d4f41f 0000000000000010 0006030203190000 ffff00ff0000ff00 
[17582052845.998711] GPR12: 0000000000000e80 c00000000faaf700 c00000000000d3b8 0000000000000000 
[17582052845.998711] GPR16: 0000000000000000 0000000000000000 0000000000000000 0000000000000000 
[17582052845.998711] GPR20: 0000000000000000 0000000000000000 0000000000000000 0000000000000000 
[17582052845.998711] GPR24: c000000001134688 c0000000010b3680 c000000001095b70 0000000000000005 
[17582052845.998711] GPR28: c000000001a49df8 c0000000016d8180 c000000001a49df0 c00000000162a300 
[17582052845.998711] CFAR: c0000000000ec818 DAR: 0006030203190010 DSISR: 02000002 SOFTE: 0 
[17582052845.998711] GPR00: 0000000000000001 c00000003fcc3ef0 c0000000016eaf00 007fffffffffeb25 
[17582052845.998711] GPR04: c0000017208d5540 c0000016d4185900 0000000000000000 ffffffffffffffff 
[17582052845.998711] GPR08: 0040000003d4f41f 0000000000000010 0006030203190000 ffff00ff0000ff00 
[17582052845.998711] GPR12: 0000000000000e80 c00000000faaf700 c00000000000d3b8 0000000000000000 
[17582052845.998711] GPR16: 0000000000000000 0000000000000000 0000000000000000 0000000000000000 
[17582052845.998711] GPR20: 0000000000000000 0000000000000000 0000000000000000 0000000000000000 
[17582052845.998711] GPR24: c000000001134688 c0000000010b3680 c000000001095b70 0000000000000005 
[17582052845.998711] GPR28: c000000001a49df8 c0000000016d8180 c000000001a49df0 c00000000162a300 
[17582052845.999059] NIP [c0000000000ec87c] kvmppc_got_guest+0x33c/0x358
[17582052845.999059] NIP [c0000000000ec87c] kvmppc_got_guest+0x33c/0x358
[17582052845.999061] LR [c0000000000ec6ac] kvmppc_got_guest+0x16c/0x358
[17582052845.999061] LR [c0000000000ec6ac] kvmppc_got_guest+0x16c/0x358
[17582052845.999062] Call Trace:
[17582052845.999062] Call Trace:
[17582052845.999063] Instruction dump:
[17582052845.999063] Instruction dump:
[17582052845.999081] 7d1e4ba6 4c00012c 7c764aa6 60000000 2c230200 418001a4 e94d0948 282a0000 
[17582052845.999081] 7d1e4ba6 4c00012c 7c764aa6 60000000 2c230200 418001a4 e94d0948 282a0000 
[17582052845.999098] 4182002c e9641ca0 39200010 7c0006ac <7d6957ea> 81641c98 39200018 7d69572a 
[17582052845.999098] 4182002c e9641ca0 39200010 7c0006ac <7d6957ea> 81641c98 39200018 7d69572a 
[17582052845.999103] ---[ end trace d7bec06b0361fa31 ]---
[17582052845.999103] ---[ end trace d7bec06b0361fa31 ]---
[52599.106899414,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf004202c
[52599.106906294,6] IPMI: dropping non severe PEL event
[52599.108915426,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf0042608
[52599.108919537,6] IPMI: dropping non severe PEL event
[52599.109865866,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf0042870
[52599.109917375,6] IPMI: dropping non severe PEL event
[52599.112134341,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf0042f9c
[52599.112185284,6] IPMI: dropping non severe PEL event
[52599.114931198,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf00434d8
[52599.114988842,6] IPMI: dropping non severe PEL event
[52599.116387867,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf00437ac
[52599.116449408,6] IPMI: dropping non severe PEL event
[52599.116949056,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf0043988
[52599.116953162,6] IPMI: dropping non severe PEL event
[52599.117065314,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf00439bc
[52599.117069302,6] IPMI: dropping non severe PEL event
[52599.117144949,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf00439d0
[52599.117148991,6] IPMI: dropping non severe PEL event
[52599.117239574,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf00439f8
[52599.117243513,6] IPMI: dropping non severe PEL event
[52599.117349660,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf0043a28
[52599.117353695,6] IPMI: dropping non severe PEL event
[52599.117450491,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf0043a50
[52599.117454555,6] IPMI: dropping non severe PEL event
[52599.117546738,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf0043a6c
[52599.117550670,6] IPMI: dropping non severe PEL event
[52599.117659107,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf0043a94
[52599.117663150,6] IPMI: dropping non severe PEL event
[52599.117789097,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf0043ac4
[52599.117793129,6] IPMI: dropping non severe PEL event
[52599.117907166,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf0043b00
[52599.117911067,6] IPMI: dropping non severe PEL event
[52599.117996709,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf0043b10
[52599.118000811,6] IPMI: dropping non severe PEL event
[52599.118099055,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf0043b7c
[52599.118102991,6] IPMI: dropping non severe PEL event
[52599.118216041,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf0043c44
[52599.118220009,6] IPMI: dropping non severe PEL event
[52599.118301037,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf0043c54
[52599.118305072,6] IPMI: dropping non severe PEL event
[52599.118410368,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf0043c6c
[52599.118414312,6] IPMI: dropping non severe PEL event
[52599.118533987,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf0043cac
[52599.118537872,6] IPMI: dropping non severe PEL event
[52599.118650465,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf0043e10
[52599.118654364,6] IPMI: dropping non severe PEL event
[52599.118750247,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf0043e80
[52599.118754257,6] IPMI: dropping non severe PEL event
[52599.118872257,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf0043ee8
[52599.118876035,6] IPMI: dropping non severe PEL event
[52599.118957323,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf0043f14
[52599.118961454,6] IPMI: dropping non severe PEL event
[52599.119078183,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf0044014
[52599.119082019,6] IPMI: dropping non severe PEL event
[52599.139505437,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf006c490
[52599.139509490,6] IPMI: dropping non severe PEL event
[52599.139645663,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf006c71c
[52599.139649582,6] IPMI: dropping non severe PEL event
[52599.139771874,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf006c910
[52599.139775921,6] IPMI: dropping non severe PEL event
[52599.139906154,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf006cb74
[52599.139910180,6] IPMI: dropping non severe PEL event
[52599.140039139,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf006cdbc
[52599.140043150,6] IPMI: dropping non severe PEL event
[52599.140135098,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf006ceac
[52599.140139212,6] IPMI: dropping non severe PEL event
[52599.140221121,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf006cf90
[52599.140225037,6] IPMI: dropping non severe PEL event
[52599.160496554,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf0094ffc
[52599.160500683,6] IPMI: dropping non severe PEL event
[52599.170320486,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf00a853c
[52599.170324571,6] IPMI: dropping non severe PEL event
[52599.170434754,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf00a863c
[52599.170438812,6] IPMI: dropping non severe PEL event
[52599.170573787,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf00a8858
[52599.170577878,6] IPMI: dropping non severe PEL event
[52599.171176114,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf00a91a0
[52599.171216634,6] IPMI: dropping non severe PEL event
[52599.172080920,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf00a94a4
[52599.172155896,6] IPMI: dropping non severe PEL event
[52599.173092248,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf00a972c
[52599.173176233,6] IPMI: dropping non severe PEL event
[52599.174293875,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf00a9a20
[52599.174390758,6] IPMI: dropping non severe PEL event
[52599.175268435,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf00a9df0
[52599.175319089,6] IPMI: dropping non severe PEL event
[52599.176076090,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf00aab80
[52599.176080795,6] IPMI: dropping non severe PEL event
[52599.183858412,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf00b9630
[52599.183862538,6] IPMI: dropping non severe PEL event
[52599.193283668,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf00bfffc
[52599.193287604,6] IPMI: dropping non severe PEL event
[52599.246789418,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf0135018
[52599.246793518,6] IPMI: dropping non severe PEL event
[52599.287481444,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf0184ffc
[52599.287485309,6] IPMI: dropping non severe PEL event
[52599.320016805,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf01c4ffc
[52599.320020849,6] IPMI: dropping non severe PEL event
[52599.340302621,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf01ecc78
[52599.340306535,6] IPMI: dropping non severe PEL event
[52599.352750115,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf0205230
[52599.352754122,6] IPMI: dropping non severe PEL event
[52599.352916909,7] SLW: restore spr:0x13e on c:0xa with 0x40400001d2f012
[52599.352916911,7] SLW: restore spr:0x13e on c:0x9 with 0x40400001d2f012
[52599.352923784,7] SLW: restore spr:0x13e on c:0xa with 0x40400001d2d012
[52599.352927357,7] SLW: restore spr:0x13e on c:0x9 with 0x40400001d2d012
[52599.352916995,7] SLW: restore spr:0x13e on c:0xb with 0x40400001d2f012
[52599.352933189,7] SLW: restore spr:0x13e on c:0x9 with 0x40400001d2f012
[52599.352936520,7] SLW: restore spr:0x13e on c:0xb with 0x40400001d2d012
[52599.352930104,7] SLW: restore spr:0x13e on c:0xa with 0x40400001d2f012
[52599.352939336,7] SLW: restore spr:0x13e on c:0x9 with 0x40400001d2d012
[52599.352945944,7] SLW: restore spr:0x13e on c:0xa with 0x40400001d2d012
[52599.352943051,7] SLW: restore spr:0x13e on c:0xb with 0x40400001d2f012
[52599.352951082,7] SLW: restore spr:0x13e on c:0xb with 0x40400001d2d012
[52599.355777567,7] SLW: restore spr:0x13e on c:0x9 with 0x40400001d2f012
[52599.355777570,7] SLW: restore spr:0x13e on c:0xa with 0x40400001d2f012
[52599.355777573,7] SLW: restore spr:0x13e on c:0xb with 0x40400001d2f012
[52599.355783129,7] SLW: restore spr:0x13e on c:0x9 with 0x40400001d2d012
[52599.355787268,7] SLW: restore spr:0x13e on c:0xa with 0x40400001d2d012
[52599.355794238,7] SLW: restore spr:0x13e on c:0x9 with 0x40400001d2f012
[52599.355790670,7] SLW: restore spr:0x13e on c:0xb with 0x40400001d2d012
[52599.355799503,7] SLW: restore spr:0x13e on c:0x9 with 0x40400001d2d012
[52599.355797210,7] SLW: restore spr:0x13e on c:0xa with 0x40400001d2f012
[52599.355803420,7] SLW: restore spr:0x13e on c:0xb with 0x40400001d2f012
[52599.355808049,7] SLW: restore spr:0x13e on c:0xa with 0x40400001d2d012
[52599.355808694,7] SLW: restore spr:0x13e on c:0xb with 0x40400001d2d012
[52600.018187258,7] SLW: restore spr:0x13e on c:0x9 with 0x40400001d2f012
[52600.018187263,7] SLW: restore spr:0x13e on c:0xb with 0x40400001d2f012
[52600.018192428,7] SLW: restore spr:0x13e on c:0x9 with 0x40400001d2d012
[52600.018195581,7] SLW: restore spr:0x13e on c:0xb with 0x40400001d2d012
[52600.018199243,7] SLW: restore spr:0x13e on c:0x9 with 0x40400001d2f012
[52600.018202478,7] SLW: restore spr:0x13e on c:0xb with 0x40400001d2f012
[52600.018204527,7] SLW: restore spr:0x13e on c:0x9 with 0x40400001d2d012
[52600.018187259,7] SLW: restore spr:0x13e on c:0xa with 0x40400001d2f012
[52600.018207643,7] SLW: restore spr:0x13e on c:0xb with 0x40400001d2d012
[52600.018211956,7] SLW: restore spr:0x13e on c:0xa with 0x40400001d2d012
[52600.018213688,7] SLW: restore spr:0x13e on c:0xa with 0x40400001d2f012
[52600.018214794,7] SLW: restore spr:0x13e on c:0xa with 0x40400001d2d012
[52600.022983437,7] SLW: restore spr:0x13e on c:0x9 with 0x40400001d2f012
[52600.022983445,7] SLW: restore spr:0x13e on c:0xa with 0x40400001d2f012
[52600.022983442,7] SLW: restore spr:0x13e on c:0xb with 0x40400001d2f012
[52600.022989404,7] SLW: restore spr:0x13e on c:0x9 with 0x40400001d2d012
[52600.022992591,7] SLW: restore spr:0x13e on c:0xa with 0x40400001d2d012
[52600.022998505,7] SLW: restore spr:0x13e on c:0x9 with 0x40400001d2f012
[52600.023000741,7] SLW: restore spr:0x13e on c:0xa with 0x40400001d2f012
[52600.022994882,7] SLW: restore spr:0x13e on c:0xb with 0x40400001d2d012
[52600.023006635,7] SLW: restore spr:0x13e on c:0xa with 0x40400001d2d012
[52600.023010747,7] SLW: restore spr:0x13e on c:0xb with 0x40400001d2f012
[52600.023003848,7] SLW: restore spr:0x13e on c:0x9 with 0x40400001d2d012
[52600.023015642,7] SLW: restore spr:0x13e on c:0xb with 0x40400001d2d012
[52600.093963483,7] SLW: restore spr:0x13e on c:0xa with 0x40400001d2f012
[52600.093963487,7] SLW: restore spr:0x13e on c:0xb with 0x40400001d2f012
[52600.093969240,7] SLW: restore spr:0x13e on c:0xa with 0x40400001d2d012
[52600.093972090,7] SLW: restore spr:0x13e on c:0xb with 0x40400001d2d012
[52600.093975734,7] SLW: restore spr:0x13e on c:0xa with 0x40400001d2f012
[52600.093979045,7] SLW: restore spr:0x13e on c:0xb with 0x40400001d2f012
[52600.093963491,7] SLW: restore spr:0x13e on c:0x9 with 0x40400001d2f012
[52600.093981690,7] SLW: restore spr:0x13e on c:0xa with 0x40400001d2d012
[52600.093984749,7] SLW: restore spr:0x13e on c:0xb with 0x40400001d2d012
[52600.093987861,7] SLW: restore spr:0x13e on c:0x9 with 0x40400001d2d012
[52600.093993762,7] SLW: restore spr:0x13e on c:0x9 with 0x40400001d2f012
[52600.093994857,7] SLW: restore spr:0x13e on c:0x9 with 0x40400001d2d012
[52600.094666217,7] SLW: restore spr:0x13e on c:0x9 with 0x40400001d2f012
[52600.094666222,7] SLW: restore spr:0x13e on c:0xa with 0x40400001d2f012
[52600.094666218,7] SLW: restore spr:0x13e on c:0xb with 0x40400001d2f012
[52600.094672368,7] SLW: restore spr:0x13e on c:0x9 with 0x40400001d2d012
[52600.094675263,7] SLW: restore spr:0x13e on c:0xa with 0x40400001d2d012
[52600.094681524,7] SLW: restore spr:0x13e on c:0x9 with 0x40400001d2f012
[52600.094684404,7] SLW: restore spr:0x13e on c:0xa with 0x40400001d2f012
[52600.094678204,7] SLW: restore spr:0x13e on c:0xb with 0x40400001d2d012
[52600.094687770,7] SLW: restore spr:0x13e on c:0x9 with 0x40400001d2d012
[52600.094691709,7] SLW: restore spr:0x13e on c:0xa with 0x40400001d2d012
[52600.094694938,7] SLW: restore spr:0x13e on c:0xb with 0x40400001d2f012
[52600.094699411,7] SLW: restore spr:0x13e on c:0xb with 0x40400001d2d012
[52600.188198623,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf04ac75c
[52600.188202638,6] IPMI: dropping non severe PEL event
[52600.188371468,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf04acb00
[52600.188375487,6] IPMI: dropping non severe PEL event
[52600.188537251,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf04ace24
[52600.188541192,6] IPMI: dropping non severe PEL event
[52600.188735332,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf04ad26c
[52600.188739369,6] IPMI: dropping non severe PEL event
[52600.188909943,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf04ad608
[52600.188914059,6] IPMI: dropping non severe PEL event
[52600.189038257,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf04ad84c
[52600.189042314,6] IPMI: dropping non severe PEL event
[52600.189158758,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf04ada34
[52600.189162823,6] IPMI: dropping non severe PEL event
[52600.189285226,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf04adc64
[52600.189289391,6] IPMI: dropping non severe PEL event
[52600.189427834,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf04adf10
[52600.189431786,6] IPMI: dropping non severe PEL event
[52600.189609562,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf04ae2f0
[52600.189613678,6] IPMI: dropping non severe PEL event
[52600.189735779,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf04ae520
[52600.189739866,6] IPMI: dropping non severe PEL event
[52600.189874036,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf04ae7ac
[52600.189878105,6] IPMI: dropping non severe PEL event
[52600.190007773,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf04ae9c0
[52600.190011730,6] IPMI: dropping non severe PEL event
[52600.190093355,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf04ae9f4
[52600.190097262,6] IPMI: dropping non severe PEL event
[52600.190177125,3] LPC[000]: Got SYNC no-response error. Error address reg: 0xf04aea24
```

**Comment by amboar** [comment] 2019-07-15 05:49
@pridhiviraj any idea what was happening to the BMC at the time? This looks like the LPC2AHB bridge died somehow.

**Comment by amboar** [comment] 2019-07-15 06:21
Actually, given the addresses mentioned, it might be a skiboot bug as the PNOR (hiomap or not) should be mapped at the top of the LPC FW address space. Was this on P8 or P9?

**Comment by hegdevasant** [comment] 2019-07-15 08:19
I think I have seen few reports related "LPC SYNC no-response error" on P9. But I don't have a way to reproduce this issue.

Between, FYI @pridhiviraj left IBM few months ago. So if we are not able to reproduce then best thing we can do is to close this issue.


-Vasant

**Comment by amboar** [comment] 2019-07-16 00:43
@hegdevasant they can occur for a variety of reasons. A common one recently was boot progress updates on port 80/81/82. Given @pridhiviraj's departure, the lack of information and the age of the issue I suggest we close this for the time being, reopen it if we encounter the same errors, and open separate issues for other no-response failures (based on the failing address).

**Closed** 2019-07-16 00:44 UTC
Labels: NEEDINFO, bug
